# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
production:
  encoding: utf8
  adapter: mysql
  host: localhost
  port: 3306
  database: walnut_production
  username: rails
  password: 1ndus7ry!
